site_name: Caderno de Estudos - Enrico
site_description: Minha evolução em programação, matemática e dados
site_author: Enrico Aoyama

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Modo escuro

    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Modo claro

plugins:
  - search
nav:
  - Início: index.md
  - Sobre: sobre.md

  - Programação:
      - Python:
          - Básico: programacao/python/basico.md
          - Listas: programacao/python/listas.md
      - R:
          - Básico: programacao/r/basico.md

  - Matemática:
      - Álgebra: matematica/algebra.md
      - Estatística: matematica/estatistica.md